FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10-slim

RUN apt-get -y update
RUN apt-get install -y --fix-missing build-essential cmake libpq-dev curl

RUN pip install 'poetry==1.4.1'

ENV MODULE_NAME="lm_backend.main"

COPY ./pyproject.toml /app/
COPY ./poetry.lock /app/

RUN poetry config virtualenvs.create false --local
RUN poetry install --no-root

VOLUME /app/lm_backend
