name: license-manager-agent
base: core24
version: '0.2.0'
summary: The License Manager Agent snap
adopt-info: metadata
license: MIT
description: |
  The License Manager Agent Snap deploys the License Manager Agent Python package on your host system. This agent is an essencial component of the License Manager suite.

  This snap requires a few configuration values to be set before it can be used. These values are:
  - backend-base-url: The URL of the License Manager API server where the agent will send its data. Setting/unsetting this value is more interesting when using the snap in a development environment; do not change it otherwise.

  - oidc-domain: The domain of the OIDC server that the agent will use for authentication. Setting/unsetting this
    value is more interesting when using the snap in a development environment; do not change it otherwise.

  - oidc-client-id: The client ID of the OIDC application that the agent will use for authentication.

  - oidc-client-secret: The client secret of the OIDC application that the agent will use for authentication.

  - sacctmgr-path: The absolute path to the *sacctmgr* command on the host system. This is optional and defaults to /usr/bin/sacctmgr.

  - scontrol-path: The absolute path to the *scontrol* command on the host system. This is optional and defaults to /usr/bin/scontrol.

  - squeue-path: The absolute path to the *squeue* command on the host system. This is optional and defaults to /usr/bin/squeue.

  - lmutil-path: Absolute path to the binary for lmutil (needed for FlexLM licenses). Defaults to /usr/local/bin/lmutil.

  - rlmutil-path: Absolute path to the binary for rlmutil (needed for RLM licenses). Defaults to /usr/local/bin/rlmutil.

  - lsdyna-path: Absolute path to the binary for lstc_qrun (needed for LS-Dyna licenses). Defaults to /usr/local/bin/lsdyna.

  - lmxendutil-path: Absolute path to the binary for lmxendutil (needed for LM-X licenses). Defaults to /usr/local/bin/lmxendutil.

  - olixtool-path: Absolute path to the binary for olixtool (needed for OLicense licenses). Defaults to /usr/local/bin/olixtool.

  - reservation-identifier: Reservation name used when doing the reconciliation. Defaults to *license-manager-reservation*.

  - lm_user: System user name used when creating reservations. Defaults to *license-manager*.

  - stat-interval: Interval in seconds used to report the cluster status to the API. Defaults to 60.

  - tool-timeout: Timeout in seconds for the license server binaries. Defaults to 6.

  - encoding: Encoding used for decoding the output of the license server binaries. Defaults to *utf-8*.

grade: stable
confinement: classic

parts:
  license-manager-agent:
    source: .
    plugin: python
    python-packages:
    - license-manager-agent
    build-packages:
    - python3
    - libapt-pkg-dev
    - gcc
    - g++
    - dpkg-dev
    stage-packages:
    - python3.12-minimal
    - python3.12-venv
    - libpython3.12-minimal
    - libpython3.12-stdlib
    build-attributes:
    - enable-patchelf

  hooks:
    plugin: dump
    source: hooks
    organize:
      bin/: snap/hooks/

  metadata:
    plugin: nil
    override-pull: |
      craftctl default
      COMMIT_SHA=$(cat $SNAPCRAFT_PROJECT_DIR/sha/commit-sha.txt)
      craftctl set version="$(craftctl get version)-$COMMIT_SHA"

  wrappers:
    plugin: dump
    source: wrappers/
    source-type: local

apps:
  daemon:
    command: bin/license-manager-agent
    daemon: simple
    install-mode: disable
    environment:
      PYTHONPATH: "$SNAP/lib/python3.12/site-packages:${PYTHONPATH}"

  start:
    command: commands/daemon.start
    daemon: simple
    install-mode: disable

  stop:
    command: commands/daemon.stop
    daemon: simple
    install-mode: disable

  restart:
    command: commands/daemon.restart
    daemon: simple
    install-mode: disable
