"""First migration

Revision ID: bf1e9e9a9e5f
Revises: 
Create Date: 2021-08-03 11:54:19.474407

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bf1e9e9a9e5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('features', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('license_servers', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('license_server_type', sa.String(), nullable=True),
    sa.Column('grace_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_feature', sa.String(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.CheckConstraint('used<=total'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_feature')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('product_feature', sa.String(), nullable=True),
    sa.Column('booked', sa.Integer(), nullable=True),
    sa.Column('lead_host', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('cluster_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('license')
    op.drop_table('config')
    # ### end Alembic commands ###
