FROM python:3.12-slim-bullseye

WORKDIR /app

RUN apt update && apt install -y curl libpq-dev gcc
RUN pip install poetry==1.4.0

COPY ./pyproject.toml ./poetry.lock /app/

RUN poetry install --no-root && rm -rf "$POETRY_CACHE_DIR"

COPY ./alembic /app/alembic
COPY ./lm_api /app/lm_api

CMD ["uvicorn", "lm_api.main:app", "--host", "0.0.0.0", "--port", "80", "--loop", "asyncio"]
