version: "3.9"
services:

  postgres-back:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    user: postgres

  lm-simulator:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres-back:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:123@postgres-back:5432/postgres}
    ports:
      - "8000:8000"
    command: uvicorn lm_simulator.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
