version: "3.9"
services:

  postgres-back:
    image: postgres:14.1
    environment:
      POSTGRES_DB: local-db
      POSTGRES_USER: local-user
      POSTGRES_PASSWORD: local-pswd
    ports: ["5432:5432"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  lm-simulator:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres-back:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres-back
      DATABASE_USER: local-user
      DATABASE_PSWD: local-pswd
      DATABASE_NAME: local-db
      DATABASE_PORT: 5432

    ports: ["8000:8000"]
    command: uvicorn lm_simulator.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
