"""Add client_id column to config table (ARMADA-468)

Revision ID: 5308f26e8b60
Revises: 0b3788c540bb
Create Date: 2022-05-25 16:25:30.213962

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "5308f26e8b60"
down_revision = "0b3788c540bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # it is needed to manually change the values in the database after the migration gets complete.
    # Due to the nature of this column, there might be many different client ids, so right now
    # there's no other way to fill out this column. Leaving it as nullable=True drives to inconsistency
    # between the database and the API, which raises internal error. This behaviour was tested and checked
    op.add_column("config", sa.Column("client_id", sa.String(), nullable=False, server_default="dummy-value"))
    op.create_index(op.f("ix_config_client_id"), "config", ["client_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_config_client_id"), table_name="config")
    op.drop_column("config", "client_id")
    # ### end Alembic commands ###
