apiVersion: v1
kind: ConfigMap
metadata:
  name: lm-api
  labels:
    k8s-app: lm
data:
  ARMASEC_DOMAIN: {{ .Values.auth.armasecDomain | quote }}
  {{- if .Values.sentry.enabled }}
  SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
  {{- end }}
  SENTRY_TRACING_SAMPLE_RATE: {{ .Values.sentry.tracesSampleRate | quote }}
  SENTRY_PROFILING_SAMPLE_RATE: {{ .Values.sentry.profilesSampleRate | quote }}
