{{- if .Values.awsSecrets.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-creds
data:
  key-id: {{ .Values.awsSecrets.creds.keyId }}
  access-secret: {{ .Values.awsSecrets.creds.accessSecret }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-gen
spec:
  region: {{ .Values.awsSecrets.region }}
  role: {{ .Values.awsSecrets.role }}
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: "aws-creds"
        key: "key-id"
      secretAccessKeySecretRef:
        name: "aws-creds"
        key: "access-secret"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "ecr-secret"
spec:
  refreshInterval: "1h"
  target:
    name: ecr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ `{{ .proxy_endpoint }}` }}":{"username":"{{ `{{ .username }}` }}","password":"{{ `{{ .password }}` }}","auth":"{{ `{{ printf "%s:%s" .username .password | b64enc }}` }}"}}}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: "ecr-gen"
{{- end }}
