apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lm-postgres-encrypted-backup-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    k8s-app: lm
spec:
  storageClassName: {{ .Values.config.lmApi.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.config.lmApi.storageSize }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: lm-postgres-primary-password
  labels:
    k8s-app: lm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  length: 42
  digits: 10
  symbols: 10
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: lm-postgres-replica-password
  labels:
    k8s-app: lm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  length: 42
  digits: 10
  symbols: 10
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lm-kubegres-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    k8s-app: lm
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: k8s-secretsmanager
    kind: ClusterSecretStore
  target:
    name: lm-kubegres-credentials
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "lm-postgres-primary-password"
      rewrite:
        - regexp:
            source: "(.*)"
            target: "primary-password"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "lm-postgres-replica-password"
      rewrite:
        - regexp:
            source: "(.*)"
            target: "replica-password"
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: lm-api-kubegres-encrypted
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    k8s-app: lm
spec:
  replicas: 2
  image: public.ecr.aws/omnivector-solutions/postgres:14.1
  database:
    size: {{ .Values.config.lmApi.storageSize }}
    storageClassName: {{ .Values.config.lmApi.storageClassName }}
    volumeMount: /var/lib/postgresql/data
  backup:
    schedule: "{{ .Values.config.lmApi.backupSchedule }}"
    pvcName: lm-postgres-encrypted-backup-pvc
    volumeMount: /var/lib/backup
  resources:
    {{- toYaml .Values.config.lmApi.dbResources | nindent 4 }}
  scheduler:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: eks.amazonaws.com/capacityType
                  operator: In
                  values:
                    - ON_DEMAND
                - key: {{ .Values.config.lmApi.kubegresNodeAffinityNodeSelectorTerms.key }}
                  operator: In
                  values:
                    - {{ .Values.config.lmApi.kubegresNodeAffinityNodeSelectorTerms.value }}
      {{- if .Values.config.lmApi.dbHighAvailability }}
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchLabels:
                  app: lm-api-kubegres-encrypted
          - weight: 90
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: lm-api-kubegres-encrypted
      {{- end }}
    tolerations:
    - key: "vantagecompute.ai/highcpu"
      operator: "Equal"
      value: "true"
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: lm-kubegres-credentials
          key: primary-password
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: lm-kubegres-credentials
          key: replica-password
    - name: POSTGRES_USER
      value: omnivector
    - name: POSTGRES_DB
      value: lm
