apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lm-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lm-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lm-api-kubegres-primary
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: lm-api-postgres-cluster
      replicationRole: primary
