apiVersion: v1
kind: Service
metadata:
  name: lm-api
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /lm/health
    alb.ingress.kubernetes.io/success-codes: "204"
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: lm-api
